### ISSUE TITLE
测试反馈

### ISSUE THREAD

**Issue by blackmatch** [axetroy/sms-boom#12]
**I'm submitting a ...**  (check one with "x")

- [x] bug report => search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request

**Current behavior**

1.有些已经发送成功了，但是终端显示**failed!**
2.需要Node.js8.3.0+，否则会报如下错误：
<img width="620" alt="2017-10-31 13 26 38" src="https://user-images.githubusercontent.com/12443954/32208720-39d35f4c-bdd2-11e7-9b6f-89e579af4b17.png">

> 已提交更新README的PR。

**Expected behavior**

1.正确提示是否发送成功。
2.声明需要依赖的Node.js版本

**More detail**

附上我测试的一些图，挺给力的：

<img width="764" alt="2017-10-31 13 29 35" src="https://user-images.githubusercontent.com/12443954/32208830-10191704-bdd3-11e7-8fb2-1feb24862b30.png">

![wechatimg10](https://user-images.githubusercontent.com/12443954/32208836-16753bb4-bdd3-11e7-8436-e4a12202f45b.jpeg)

**Please tell us about your environment:**
masOS Sierra 10.12.6 全局安装，在终端中使用。

**Comment by axetroy** [comment]
感谢反馈。

下一版本中会移除``...``操作符。
之后NodeJs版本应该需要>=7.6，需要``async await``的支持。

至于说提示发送失败，但是实际上还是收到了验证码这个，图上没看出来。

**Comment by blackmatch** [comment]
@axetroy 图没截完，比如说终端上显示『优酷』provider是fail，但是确实收到了『优酷』的验证码。

**Comment by axetroy** [comment]
@blackmatch 
本质上，只要Provider的resolve函数走通了，没有报错，那么就认为是发送成功了

基本上每个resolve函数都有检测是否发送成功的函数，那应该是那一步错了，或者优酷改了页面元素

**Comment by axetroy** [comment]
源码很简单的，欢迎PR

**Comment by blackmatch** [comment]
好的，有空学习学习，我一开始也想做这样的项目，是奔着识别验证码去的，但是后来发现识别验证码这方面的可用的资源不多，难度颇大，后来就没有继续下去。现在Node.js已经出了8.x的LTS，所以版本支持上可以不用那么拘谨了 :smile:
