### ISSUE TITLE
全局安装报权限问题

### ISSUE THREAD

**Issue by blackmatch** [axetroy/sms-boom#13]
使用root+sudo用户全局安装报错，如下：

![wechatimg109](https://user-images.githubusercontent.com/12443954/32311004-2d2e04f2-bf64-11e7-92d5-485539e8f608.jpeg)

**Comment by axetroy** [comment]
看起来像是没有权限设置环境变量

**Comment by blackmatch** [comment]
@axetroy 这个问题我经过一番搜索之后得到了解决方案。如下：

1.先执行：`npm config set unsafe-perm=true`

2.然后安装：`sudo npm install smsboomer -g`

亲测可用：

![2017-11-16 23 07 16](https://user-images.githubusercontent.com/12443954/32898672-bd6d2bae-cb23-11e7-801e-4a32836172a7.png)

我的环境：

OS: macOS High Sierra
Node version: 9.2.0

详情看这里

[https://github.com/GoogleChrome/puppeteer/issues/1303](https://github.com/GoogleChrome/puppeteer/issues/1303)

**Comment by axetroy** [comment]
@blackmatch 
感谢你的反馈，以及提供的解决方案。:+1:
