### ISSUE TITLE
ERROR: networkIdleTimeout option is no longer supported

### ISSUE THREAD

**Issue by blackmatch** [axetroy/sms-boom#18]
**I'm submitting a ...**  (check one with "x")

- [x] bug report => search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request

**Current behavior**

I have install smsboomer globally, when I run 'smsboomer xxxx', error pop up:

```
[INFO]: 进入到 向日葵 http://z.xiangrikui.com/zn/phone/submit?rand_key=224594
{ AssertionError [ERR_ASSERTION]: ERROR: networkIdleTimeout option is no longer supported.
    at Console.assert (console.js:196:23)
    at new NavigatorWatcher (/usr/local/lib/node_modules/smsboomer/node_modules/puppeteer/lib/NavigatorWatcher.js:27:13)
    at Page.goto (/usr/local/lib/node_modules/smsboomer/node_modules/puppeteer/lib/Page.js:464:21)
    at App.run (/usr/local/lib/node_modules/smsboomer/app/app.js:115:27)
    at <anonymous>
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
```

**Expected behavior**

`smsboomer xxx` can work.

**More detail**

I think this is because puppeteer is now update to 0.13.0, see [this pr](https://github.com/GoogleChrome/puppeteer/pull/1355).

**Please tell us about your environment:**

macOS High Sierra
Node.js 9.2.0

**Comment by axetroy** [comment]
puppeteer当前没有发布正式版，有一些API变更不兼容。

**Comment by axetroy** [comment]
看了一下puppeteer的更新日志。

确实是这样，这个事件被移除了
