### ISSUE TITLE
语音验证码的功能也不错，希望可以加上。

### ISSUE THREAD

**Issue by aloveric** [axetroy/sms-boom#25]
RT

这里有三个：
https://www.1000.com/reg
http://www.baixing.com/oz/verify/reg
https://cloud.shinewonder.com/user/registion

**Comment by axetroy** [comment]
@aloveric 
谢谢提供短信源
> https://www.1000.com/reg
> http://www.baixing.com/oz/verify/reg
这两个已经有了

> https://cloud.shinewonder.com/user/registion
这个需要验证码，不做需要验证码的

**Comment by aloveric** [comment]
@axetroy 奥，好的不好意思啊，close吧~~
