### ISSUE TITLE
又找到几个网站，看看能不能加进去~

### ISSUE THREAD

**Issue by WongCM** [axetroy/sms-boom#26]
http://www.zongheng.com/

http://www.jaja123.com/web/register

https://passport.yhd.com/passport/register_input.do

http://shop.yinyuetai.com/

https://passport.xidibuy.com/reg/index

https://passport.ingping.com/reg/index?retUrl=https%3A%2F%2Fwww.ingping.com

http://www.happigo.com/register/

http://www.homekoo.com/zhixiao/cuxiao/index.php  （页面底部）

http://login.haodou.com/register.php  (拖动到最右边进行验证)

http://mall.slswd.com/register!toPc.htm   (拖动到最右边进行验证)

https://passport.zhe800.com/users/signup  (拖动到最右边进行验证)

**Comment by axetroy** [comment]
@WongCM 
非常感谢提供。众人拾柴火焰高 👍

**Comment by axetroy** [comment]
已添加到短信源里面

http://www.zongheng.com/
> 4be0ce5f4fb4d2dc488da633fbbb1e42e05de81a

http://www.jaja123.com/web/register
> bf991b50b767c9d71039789fa3d31ce16b054831

https://passport.yhd.com/passport/register_input.do
> 2d1484a8df2d3beaab139764d53235e17a9213da

http://shop.yinyuetai.com/
> 9885d7274d37ce2aa3d57d6d93b3da183aecb1fb

https://passport.xidibuy.com/reg/index
> dfe033163479aa3449776c73ef9f313dcaa707a0

https://passport.ingping.com/reg/index?retUrl=https%3A%2F%2Fwww.ingping.com
> 0cd1bacf5a1ffcc097a0475c956c0309455eb472

http://www.happigo.com/register/
> 25e97bcafc2dd9e894906718591ede3cb512b99b

http://www.homekoo.com/zhixiao/cuxiao/index.php  （页面底部）
> b778ec028d01715ac3cb72465104bfaecc29aa8d

http://login.haodou.com/register.php  (拖动到最右边进行验证)
> 0939b5065d19cd11b928cdf8e6e72c3c8604a208

http://mall.slswd.com/register!toPc.htm   (拖动到最右边进行验证)
> 7fc61d09cbef4c499e73bd3933262a390bd88015

https://passport.zhe800.com/users/signup  (拖动到最右边进行验证)
> 61f71ea8c370401111b1d61c84cd47d5d7e302f7

这些已发布到新版本1.4.0里面 f882318317a92685b6ef90560acf4e2af45092ab
