### ISSUE TITLE
来提供几个新的可用作轰炸的网站

### ISSUE THREAD

**Issue by WongCM** [axetroy/sms-boom#29]
书丛：http://m.shucong.com/register

迪卡侬：https://www.decathlon.com.cn/zh/create  

企查查：http://www.qichacha.com/user_register

麦付宝：https://www.maifupay.com/register

粉笔网：http://fenbi.com/web/signup

中瑞财富：https://www.zrcaifu.com/register

乾贷网： https://www.qiandw.com/Account/RegisterNew

微盟：https://account.weimob.com/register

互亿无线：http://user.ihuyi.com/register.html

不知道叫啥的教育网站：http://study.enaea.edu.cn/customRegisterRedirect.do

凡科建站：http://jz.faisco.com/reg.html

巨人网络：http://reg.ztgame.com/ 

联拓天际：http://caigou.51book.com/caigou/manage/designatedRegistryNewSignon.in

**Comment by axetroy** [comment]
@WongCM 👍 
非常感谢，已经添加。

会在下一版本更新。

获取调用命令行进行更新

```bash
smsboomer update
```
