### ISSUE TITLE
v2

### ISSUE THREAD

**Issue by axetroy** [axetroy/sms-boom#32]
v2的计划列表

- [x] 只提供cli命令方式运行，隐藏内部细节
- [x] 进程退出时，杀掉子进程，防止进程残留
- [x] 单标签模式更改为多标签模式(并发发送短信)
- [x] 自动生成CHANGELOG
- [x] 每次都是随机的名字/邮件，防止重复
- [ ] 增加api调用模式(不模拟真实的用户注册，纯粹的api调用)
- [ ] 重构内部调用机制，provider机制不变，增加provider依旧是复制粘贴

**Comment by axetroy** [comment]
@WindomZ @blackmatch 

分享你的idea，欢迎补充

**Comment by axetroy** [comment]
TODO:

部署到服务器，把轰炸机暴露在web调用。(选用heroku或者now)

无需安装，只需要打开web，输入手机号码，即可轰炸

**Comment by blackmatch** [comment]
@axetroy 弄成API的形式，然后部署到服务器，然后撸个web直接调用API。这样我觉得是比较方便的。
