### ISSUE TITLE
有点无聊，这个坑准备弃了

### ISSUE THREAD

**Issue by axetroy** [axetroy/sms-boom#33]
因为都是一些毫无技术含量的**Dirty Job** 

挖坑完毕 :joy:

**Comment by WongCM** [comment]
大佬 弃坑了？

**Comment by 1eozhang** [comment]
这个能用吗？

**Comment by WongCM** [comment]
@1eozhang 能用

**Comment by chenyyyang** [comment]
我安装出现了一些问题...求助

**Comment by 1eozhang** [comment]
@WongCM  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1  在哪敲的呢？

**Comment by WongCM** [comment]
@1eozhang 命令行啊

**Comment by 1eozhang** [comment]
@WongCM  我直接在环境变量里边 配置了,最后可以了

**Comment by KableShow** [comment]
哈哈哈，providers文件夹里的文件是最让我服气，这工作量有点大啊
