### ISSUE TITLE
貌似没有用哦

### ISSUE THREAD

**Issue by ipengyo** [axetroy/sms-boom#6]
Error: Evaluation failed: DOMException: Failed to execute 'querySelector' on 'Document': '******' is no
t a valid selector.

**Comment by axetroy** [comment]
这个没关系，忽略掉

**Comment by JeffAAA** [comment]
也是报这个错 在浏览器界面里没有看到输入我的电话号码 ， 也木有收到短信

**Comment by axetroy** [comment]
@JeffAAA 

```bash
node index.js
```

会打开浏览器，看到输入过程哦

**Comment by ipengyo** [comment]
可能是我公司的电脑限制了复制功能，没有看到输入，到时候回家试试呢。



ipengyo@qq.com
 
发件人： Axetroy
发送时间： 2017-10-19 19:32
收件人： axetroy/sms-boom
抄送： ipengyo; Author
主题： Re: [axetroy/sms-boom] 貌似没有用哦 (#6)
@JeffAAA
node index.js
会打开浏览器，看到输入过程哦

**Comment by axetroy** [comment]
还有问题吗，不然我关闭issues了
