### ISSUE TITLE
Ubuntu 16.04 错误

### ISSUE THREAD

**Issue by L1cardo** [axetroy/sms-boom#62]
非 root 用户运行出现没有权限，如下
<img width="728" alt="2019-01-09 12 07 23" src="https://user-images.githubusercontent.com/33802186/50843247-4af9e980-13a3-11e9-8695-f547b15e790c.png">

root 用户运行又说不能启动 Chrome，如下
<img width="728" alt="2019-01-09 12 10 15" src="https://user-images.githubusercontent.com/33802186/50843300-636a0400-13a3-11e9-96f1-cc414622a971.png">

那到底怎么解决呢？？

**Comment by rsjingyan** [comment]
这种情况应该是当前用户没有执行chrome所在目录的权限
使用命令 `ls -ld <chrome所在绝对路径>` ，查看该目录属性
可以看到它的所有者应该是root,
使用命令 `sudo chown -R '<当前登陆用户>' <chrome所在绝对路径>` 更改目录所有者应该就可以了
希望能帮到你

**Comment by L1cardo** [comment]
> 这种情况应该是当前用户没有执行chrome所在目录的权限
> 使用命令 `ls -ld <chrome所在绝对路径>` ，查看该目录属性
> 可以看到它的所有者应该是root,
> 使用命令 `sudo chown -R '<当前登陆用户>' <chrome所在绝对路径>` 更改目录所有者应该就可以了
> 希望能帮到你

谢谢你的帮助，我按照你的方法搞了，然后权限问题解决了，但是又出现了新的问题。。。。。怎么办啊
这个好像就是代码的问题了。。。
<img width="1374" alt="2019-01-12 8 06 50" src="https://user-images.githubusercontent.com/33802186/51073010-d0341580-16a5-11e9-925b-65b933d06188.png">

**Comment by rsjingyan** [comment]
> > 这种情况应该是当前用户没有执行chrome所在目录的权限
> > 使用命令 `ls -ld <chrome所在绝对路径>` ，查看该目录属性
> > 可以看到它的所有者应该是root,
> > 使用命令 `sudo chown -R '<当前登陆用户>' <chrome所在绝对路径>` 更改目录所有者应该就可以了
> > 希望能帮到你
> 
> 谢谢你的帮助，我按照你的方法搞了，然后权限问题解决了，但是又出现了新的问题。。。。。怎么办啊
> 这个好像就是代码的问题了。。。
> <img alt="2019-01-12 8 06 50" width="1374" src="https://user-images.githubusercontent.com/33802186/51073010-d0341580-16a5-11e9-925b-65b933d06188.png">

目前没遇到过这个问题, 可以考虑升级一下node版本 `node v8.10.0`

**Comment by L1cardo** [comment]
> > > 这种情况应该是当前用户没有执行chrome所在目录的权限
> > > 使用命令 `ls -ld <chrome所在绝对路径>` ，查看该目录属性
> > > 可以看到它的所有者应该是root,
> > > 使用命令 `sudo chown -R '<当前登陆用户>' <chrome所在绝对路径>` 更改目录所有者应该就可以了
> > > 希望能帮到你
> > 
> > 
> > 谢谢你的帮助，我按照你的方法搞了，然后权限问题解决了，但是又出现了新的问题。。。。。怎么办啊
> > 这个好像就是代码的问题了。。。
> > <img alt="2019-01-12 8 06 50" width="1374" src="https://user-images.githubusercontent.com/33802186/51073010-d0341580-16a5-11e9-925b-65b933d06188.png">
> 
> 目前没遇到过这个问题, 可以考虑升级一下node版本 `node v8.10.0`

我的 node 是最新版本 'v11.6.0'
这个问题困扰了我将近1周了
