### ISSUE TITLE
运行一直失败

### ISSUE THREAD

**Issue by siegjan6** [axetroy/sms-boom#8]
![image](https://user-images.githubusercontent.com/26643581/32038472-b3109c90-ba5c-11e7-91f8-607b52b29063.png)

**Comment by axetroy** [comment]
请设置环境变量，这个在README里面说明了

```bash
export PHONE=目标手机号码
```

**Comment by axetroy** [comment]
@siegjan6 
请设置环境变量了再试一次，感谢反馈!:+1:

**Comment by siegjan6** [comment]
我试试，谢谢

**Comment by siegjan6** [comment]
![image](https://user-images.githubusercontent.com/26643581/32039467-cd5a16b8-ba60-11e7-882a-2a1afb48ab6d.png)
还是老样子：（
@axetroy

**Comment by axetroy** [comment]
@siegjan6 
多半是puppeteer没有下载chromium成功，这个昨晚我也遇到了。

需要多运行几次

```bash
rm -rf node_modules/
yarn autoclean
yarn
```

如果安装完依赖之后，puppeteer模块没有报错，就说明依赖安装成功了。

等会我会更新一个版本，如果依赖没有下载成功，引用puppeteer模块报错的信息，会打印出来

**Comment by siegjan6** [comment]
好的，谢谢！ 我之前npm版本过低也是报错运行部起来，升级后才可以运行
![image](https://user-images.githubusercontent.com/26643581/32040057-07af1ede-ba62-11e7-99af-51c1d24f905b.png)

**Comment by siegjan6** [comment]
![image](https://user-images.githubusercontent.com/26643581/32040196-7efc773e-ba62-11e7-918a-113a1fb1200f.png)
options.phone 是undefined
![image](https://user-images.githubusercontent.com/26643581/32040225-9b12647e-ba62-11e7-8860-6434b4acaba2.png)

**Comment by siegjan6** [comment]
`options: {"isProduction":false,"username":"abc123mmp","name":"张大爷","password":"abc123abc123","once":true}`

**Comment by siegjan6** [comment]
这样就成功了……
![image](https://user-images.githubusercontent.com/26643581/32040572-e4a0feba-ba63-11e7-9652-8c7cda73d2fd.png)
@axetroy

**Comment by axetroy** [comment]
@siegjan6 
额，不知道你输的是什么命令行...
反正我跑得起来..
要不要我用短信给你发个问候:joy:

**Comment by axetroy** [comment]
如果发现有什么好的网站，可以用作轰炸机的。

欢迎PR或者提issues联系我

**Comment by siegjan6** [comment]
求收集……我也帮你收集点。。 我朋友被轰了，要我帮他轰……  
18759948556‬
‭13805978309
帮我轰死上面2个…… 我帮你找网站

**Comment by axetroy** [comment]
**Don't be eval**
